### ISSUE TITLE
Automated Financial Reporting using Deep learning(Rnn,CNN, MLP)

### ISSUE THREAD

**Issue by ashis2004** [Niketkumardheeryan/ML-CaPsule#1007]
Automate the generation of financial reports using deep learning, reducing manual effort and errors.
1. Loading the dataset
2. Preprocessing
3. performing EDA
4. Traininng the model
5. Perform different Algorithm
pls assign it me I'm Gssoc'24 contributor

**Comment by invigorzz313** [comment]
@ashis2004 the issue is assigned.

**Comment by Sayanjones** [comment]
@invigorzz313 could you please assign me to this issue?
