### ISSUE TITLE
Different types of face detection techniques.

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#101]
Ex. 1 Using DL. 2 .Computer vision or anything else you want to add..

**Comment by sai-keerthi** [comment]
I would like to use MTCNN to perform facial detection model using deep learning and cascade classifier for detection using opencv.
can you please assign me the task.

**Comment by anubhav201241** [comment]
@Niketkumardheeryan can I work upon this ?

**Comment by sai-keerthi** [comment]
Is there any issue to be addressed??
