### ISSUE TITLE
Titan Stock Analysis

### ISSUE THREAD

**Issue by aditya-bhaumik** [Niketkumardheeryan/ML-CaPsule#1043]
Is your feature request related to a problem? Please describe.
Yes, The art of forecasting stock prices has been a difficult task for many of the researchers and analysts. Investors eagerly seek effective stock price prediction systems to guide successful investments and understand future market trends.

Describe the solution you'd like
I would like to Add the ML Models which i am gonna build like using Linear Regression and K- Means Clustering using historical stock price data and relevant financial indicators, preprocess the data, performing EDA, and check the prices, and compare the model's accuracy.

Describe alternatives you've considered
Exploring additional models like ARIMA, XGBoost, or ensemble methods for potential improvement in forecasting accuracy.

**Comment by aditya-bhaumik** [comment]
@Niketkumardheeryan please assign me this issue i have already created the applcation just need to create a pull request

**Comment by aditya-bhaumik** [comment]
@invigorzz313

**Comment by aditya-bhaumik** [comment]
Please assign me this issue only 3 days are left for gssoc

**Comment by invigorzz313** [comment]
@aditya-bhaumik there is already a stock price analysis project in the repo

**Comment by aditya-bhaumik** [comment]
@invigorzz313 isnt it for some other company 

Okay i will find some other project if you dont want stock analysis of different companies
