### ISSUE TITLE
Terrain Recognition using Transfer Learning

### ISSUE THREAD

**Issue by DarshAgrawal14** [Niketkumardheeryan/ML-CaPsule#1105]
hey @Nancyjikadra 
I am Darsh Agrawal , a fellow contributor and I would like to contribute by using Transfer learning and create a model to help various agencies label captured terrain images like mountains, coast , desserts etc . By using transfer learning we can use pre trained models like RESNET or Efficientnet and hyperparameter tune them for terrain classification for better accuracy when compared to traditional CNN models.

**Comment by Nancyjikadra** [comment]
Hi @DarshAgrawal14 , The idea is good. Just to confirm, are you asking if I’d like to team up with you on this project? Let me know!

**Comment by Nancyjikadra** [comment]
Yup, sounds good. you can proceed, looking forward to seeing the results. Happy coding! @DarshAgrawal14

**Comment by DarshAgrawal14** [comment]
hello @Nancyjikadra , can you please rename this folder "Quality Education SDG 04: Predictive Analysis" because this folder naming is creating path error while cloning repo , even if ignored while cloning the files will get deleted as they were not in the local repo :
![image](https://github.com/user-attachments/assets/f1fcac4e-021f-42cd-83c7-da9fb43dd6d4)

**Comment by DarshAgrawal14** [comment]
once the renaming is done , i think i should be able to submit PR

**Comment by DarshAgrawal14** [comment]
here is a video to show working of the model :

https://github.com/user-attachments/assets/96ea00b4-c01a-4be7-b6a9-10541acd4c31
