### ISSUE TITLE
improve the readme.md file

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#201]
* Remove the useless section and text or make it more dynamic

**Comment by Krishna841** [comment]
Hey there!!! I would like to work on this issue. Can you assign it to me?

**Comment by PurvajaDurga** [comment]
Hi, I'm Purvaja.
I would like to work on this issue.
And add the resources to the repo.
Can you assign it to me?

**Comment by Niketkumardheeryan** [comment]
wait for 1 more day ....

**Comment by srummanf** [comment]
hey, I would like to work on this issue !.

**Comment by aritra1804** [comment]
Hey I would like to work this issue for GSSOC 22

**Comment by shivam-s16** [comment]
Hey I am Shivam I am GSSOC 22 participant would like to work this issue.

**Comment by DaisyRamone14** [comment]
hey i would like to work on this issue

**Comment by Mennatallah9** [comment]
I'm a GSSoC 22 participant. I'd like to work on this issue. Can you assign it to me?

**Comment by Niketkumardheeryan** [comment]
@Krishna841 ,hey pls start working ,and do it fast otherwise i will assign this issue to others

**Comment by Krishna841** [comment]
Hey!!! How should I improve the readme? Can you give some suggestions or should I create a readme for a specific project?

**Comment by Niketkumardheeryan** [comment]
@Krishna841 make it more dynamic and explore others' readme.md  files and do it fast otherwise, we will assign it to anyone else

**Comment by Niketkumardheeryan** [comment]
@Krishna841 you have 1 more day

**Comment by Niketkumardheeryan** [comment]
@PurvajaDurga @neetra You can both can work on that...

**Comment by Ephrimgnanam** [comment]
Sir I can do good read me assign this to me 
I can make a cool and nice looking Readme for this project

**Comment by Priyanka-Chettri** [comment]
I am Priyanka Chettri GSSoC contributor 2022, please consider me next in the queue

**Comment by Niketkumardheeryan** [comment]
@Ephrimgnanam go for it....

**Comment by Niketkumardheeryan** [comment]
> I am Priyanka Chettri GSSoC contributor 2022, please consider me next in the queue

ok

**Comment by Niketkumardheeryan** [comment]
@Ephrimgnanam working on it,or should I reassign it others

**Comment by Ephrimgnanam** [comment]
Sir I'll make it tomorrow half of the work is done

**Comment by Niketkumardheeryan** [comment]
@Ephrimgnanam still working...

**Comment by Ephrimgnanam** [comment]
Sir about 50 percent work is done
