### ISSUE TITLE
Fake News Detection using ML 

### ISSUE THREAD

**Issue by Jyo561** [Niketkumardheeryan/ML-CaPsule#202]
I am going to use Julia for this so this is new one

**Comment by Jatin7385** [comment]
I could work on the Python version of Fake news detection

**Comment by Binal02Singh** [comment]
I can too work on Fake news detection using python

**Comment by Jyo561** [comment]
So i will be working on it using Julia

**Comment by Binal02Singh** [comment]
Can't we make 2 versions , 1 using julia and another one using python?

**Comment by Jyo561** [comment]
I am not a maintainer i am just a participant

**Comment by Snossy123** [comment]
I would prefer to work on this beneath GSSOC'22
Using multiple models facilitates examination between models.
Please assign this project to Maine.

**Comment by tandrimasingha** [comment]
Name: Tandrima Singha
Domain: Machine Learning
Aim: To build a model that detects fake news using NLP and Machine Learning.
GSSOC Participant

Hello sir I would like to work on this issue

**Comment by Niketkumardheeryan** [comment]
@Jyo561 @Jatin7385 start working according to your preference ....

**Comment by Niketkumardheeryan** [comment]
@Snossy123 hey, you can choose other issues or create your own issues..

**Comment by Jatin7385** [comment]
> @Jyo561 @Jatin7385 start working according to your preference ....

Will do. Thanks👍

**Comment by Jatin7385** [comment]
@Niketkumardheeryan I have made the PR for Fake News Detection. Could you go through it, and let me know if any changes are required?
