### ISSUE TITLE
Deep Learning Model for Email Spam classifier

### ISSUE THREAD

**Issue by srajan-kiyotaka** [Niketkumardheeryan/ML-CaPsule#204]
Deep Learning Model to classify whether the email is spam or not spam mail using Neural networking and NLP.

**Comment by srajan-kiyotaka** [comment]
Hii!
I am a participant in GSSOC'22. Please assign me this issue.

**Comment by Snossy123** [comment]
I want to work on this issue 
I am a participant in GSSOC'22. Please assign me this issue.

**Comment by durbar2003** [comment]
I would like to work on this issue for GSSOC'22. Please assign it

**Comment by pawansharma197** [comment]
Sir I have already completed this project can I make a pull request

**Comment by SayantikaLaskar** [comment]
I am a GSSoC'24 contributor and a machine learning engineer, could you please assign me this issue
