### ISSUE TITLE
hey I wanted to work on project of  Medicine Reader

### ISSUE THREAD

**Issue by aritra1804** [Niketkumardheeryan/ML-CaPsule#205]

**Comment by Niketkumardheeryan** [comment]
@aritra1804 pls explain briefly

**Comment by aritra1804** [comment]
Like a project that reads and extracts medicine labels and information from medicines and pill containers

**Comment by pratishthaa** [comment]
@aritra1804 Please provide a brief summary first

**Comment by aritra1804** [comment]
hey, @pratishthaa my idea is to extract and read the name and details given on medicines and pill containers. It is an OCR project basically. I would be using PaddleOCR for it

**Comment by Niketkumardheeryan** [comment]
@aritra1804 will assign this issue to others, you have 1 more day ..to make PR

**Comment by aritra1804** [comment]
Will complete by tomorrow night

**Comment by aritra1804** [comment]
hey @Niketkumardheeryan @pratishthaa i have completed my model and created a PR, pls check

**Comment by aritra1804** [comment]
Hey @Niketkumardheeryan can i close this issue,since it is merged

**Comment by aritra1804** [comment]
Thanks
