### ISSUE TITLE
Breast Cancer Prediction

### ISSUE THREAD

**Issue by Binal02Singh** [Niketkumardheeryan/ML-CaPsule#208]
This prediction model can save a lot of women from undergoing harsh cancer treatments.

I would love to help them using my ML skills, Please assign me this project.

**Comment by Snossy123** [comment]
Description
I want to do Breast Cancer Prediction.
I am a contributor to GSSoC'22. Please assign this issue to me.

Language use:
Python 
؛

**Comment by Binal02Singh** [comment]
I forgot to mention that I am participating in GSSoC'22

**Comment by AniruddhA-Omni** [comment]
Hello, Can you assign this issue to me, I have already experience in making this type of model.

**Comment by Niketkumardheeryan** [comment]
No it's already there or(similar)
