### ISSUE TITLE
Covid-19 Timeseries Analysis with multiple model

### ISSUE THREAD

**Issue by shivam-s16** [Niketkumardheeryan/ML-CaPsule#211]
Covid-19 third wave analysis using multiple models to test which one suits the best among the all . Basically to find the best model.
I would like to work on this under GSSOC'22
Using multiple model help in comparing between models .
Please assign this project to me .

**Comment by Snossy123** [comment]
Covid-19 third wave analysis victimization multiple models to check that one suits the most effective among all. to seek out the most effective model.
I would prefer to work on this beneath GSSOC'22
Using multiple models facilitates examination between models.
Please assign this project to Maine.

**Comment by Niketkumardheeryan** [comment]
@shivam-s16 Hey, pls start working ...
