### ISSUE TITLE
Credit Card Approval Prediction

### ISSUE THREAD

**Issue by UrviSinghal28** [Niketkumardheeryan/ML-CaPsule#212]
I would like to build a machine learning model for predicting credit card approvals using logistic regression.  
I would like to contribute to this project under GSSoC'22.  
Please assign this to me.

**Comment by nikhil25803** [comment]
I too want to work on this issue so can you please assign it to me?

**Comment by Niketkumardheeryan** [comment]
sorry ,its already there...
