### ISSUE TITLE
Stocks prices analysis (Time series forecasting)

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#219]

**Comment by UrviSinghal28** [comment]
Can you please assign this to me

**Comment by shivam-s16** [comment]
Can you assign me this as I am doing time series on Covid-19?

**Comment by Binal02Singh** [comment]
Hello @Niketkumardheeryan 
I have made a project on stock market prediction using various algorithms and checked their accuracy.

Can you pls assign me this project.

**Comment by Saikirannaidu225** [comment]
can I work in this issue. Stock prices analysis  can be solved using  time series forecasting. I will do this project using  different algorithms like Arima, Moving average, Auto regression,ARMA etc.
I have a good experience working with time series algorithms .Please assign me this issue.
