### ISSUE TITLE
movie or songs Recommendation system 

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#221]

**Comment by PurvajaDurga** [comment]
Hi, Can you please assign to me.

**Comment by Binal02Singh** [comment]
Hello @Niketkumardheeryan I have done this project, should I create a pull request??

**Comment by pratishthaa** [comment]
@Binal02Singh Have you worked on a Music recommendation system or a Movie recommendation system?

**Comment by monurao123456** [comment]
@Niketkumardheeryan 
sir can you please assign it to me

**Comment by Binal02Singh** [comment]
@pratishthaa I have worked on a movie recommender system, But I can make a music recommender too.

**Comment by Binal02Singh** [comment]
@pratishthaa Should I start working on the same???

**Comment by pratishthaa** [comment]
@Binal02Singh Make PR on Movie recommendation System

**Comment by pratishthaa** [comment]
@PurvajaDurga you can work on Music Recommendation System
