### ISSUE TITLE
Rock Paper Scissors Python Game

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#224]

**Comment by Mennatallah9** [comment]
I'd like to work on this issue. Can you assign it to me?

**Comment by arinjain373** [comment]
I like to work on this issue. Can you please assign it to me?

**Comment by shivam-s16** [comment]
I am also interested in this work could you please assign this to me under GSSoC'22?

**Comment by Suvodeep-Das** [comment]
Full Name: Suvodeep Das
GitHub Profile Link: https://github.com/Suvodeep-Das
Objective: Creating Rock Paper Scissors game using python.
GSSoC'22 Participant.

I would like to work on this issue.

**Comment by Niketkumardheeryan** [comment]
@Mennatallah9 start working on it
