### ISSUE TITLE
Titanic Survival prediction using Machine Learning

### ISSUE THREAD

**Issue by Suvodeep-Das** [Niketkumardheeryan/ML-CaPsule#228]
Full Name: Suvodeep Das
GitHub Profile Link: https://github.com/Suvodeep-Das
Objective: Using different Machine Learning algorithms to find out whether a person on the Titanic survived or not.
GSSoC'22 Participant.

I would like to work on this issue.

**Comment by Niketkumardheeryan** [comment]
these types of models are already there...
