### ISSUE TITLE
Fake News Detector

### ISSUE THREAD

**Issue by Suvodeep-Das** [Niketkumardheeryan/ML-CaPsule#237]
Full Name: Suvodeep Das
GitHub Profile Link: https://github.com/Suvodeep-Das
Objective: Making use of Machine Learning algorithms to detect fake news based on the content and title of news articles.
GSSoC'22 Participant.

I would like to work on this issue.

**Comment by KareemElozeiri** [comment]
hey, I am GSSOC22 participant, I would like to work on this

**Comment by Snossy123** [comment]
I am GSSOC22 participant, I want to work on this
