### ISSUE TITLE
NASA Asteroids Classification

### ISSUE THREAD

**Issue by Rutikab12** [Niketkumardheeryan/ML-CaPsule#253]
## Description:
- Find potential hazardous and non-hazardous asteroids.
- Find features responsible for claiming an asteroid to be hazardous.
-  Explore more with your own analysis.

## Dataset:
https://www.kaggle.com/shrutimehta/nasa-asteroids-classification

**Comment by KareemElozeiri** [comment]
I am a GSSOC22 participant and I would like to work on this

**Comment by KareemElozeiri** [comment]
so could I be assigned this?

**Comment by Rutikab12** [comment]
@KareemElozeiri  assigned.

**Comment by KareemElozeiri** [comment]
should I create a new sub-folder for the issue or there is already a folder to add to?

**Comment by Rutikab12** [comment]
> should I create a new sub-folder for the issue or there is already a folder to add to?

yes you have to create a subfolder and push the changes.

**Comment by KareemElozeiri** [comment]
Okay nice and what is the deadline?

**Comment by Rutikab12** [comment]
> Okay nice and what is the deadline?

There's no deadline but try to finish as early as possible as it will be convenient for you and us also.

**Comment by KareemElozeiri** [comment]
Okay very nice, thanks for your help

**Comment by KareemElozeiri** [comment]
along with the analysis, I will make DL model to predict hazardness, is that okay? @Rutikab12

**Comment by Rutikab12** [comment]
sure @KareemElozeiri

**Comment by KareemElozeiri** [comment]
Great, I have created a pull request for the analysis and later today I will add the neural net. @Rutikab12

**Comment by Rutikab12** [comment]
> Great, I have created a pull request for the analysis and later today I will add the neural net. @Rutikab12

Sure @KareemElozeiri
