### ISSUE TITLE
Startup Profit Prediction

### ISSUE THREAD

**Issue by Rutikab12** [Niketkumardheeryan/ML-CaPsule#254]
## Description:
- predict profit that a startup will make on the basis of their R&D, Administration, Marketing Spend, and State where they are based in the US.

## Dataset:
https://www.kaggle.com/sonalisingh1411/startup50

**Comment by ayushi424** [comment]
I would like to contribute on this project by using Ml model that fits best to it's accuracy on the given dataset.
Please assign me under GSSOC 2022.
@Rutikab12

**Comment by Rutikab12** [comment]
Assigned @ayushi424

**Comment by mo1998** [comment]
@Rutikab12 
Can i also work on this issue?
I will try different machine learning methodologies to increase accuracy as much as possible.
