### ISSUE TITLE
Black Friday Sales - Analysis & Prediction

### ISSUE THREAD

**Issue by Rutikab12** [Niketkumardheeryan/ML-CaPsule#256]
## Description:
- Analyze and predict the sales on Black Friday with the given dataset.

## Dataset:

https://www.kaggle.com/sdolezel/black-friday?select=train.csv

**Comment by ADITYADAS1999** [comment]
Hi, i am GGSOC 2022 contributor. Can i work with it?

**Comment by pratyush2303** [comment]
Hey! I can do this project. You can assign it to me. I am a GSSoC'22 participant.

**Comment by Diishasing** [comment]
@Rutikab12 Can I work on this issue? I would love to work on this project.

**Comment by dona-samir** [comment]
Hi, I am GSSoC'22 contributor ,I have worked with ML models before.
I can do the following
1. do data Analysis & preprocessing if need it .
2. check relation between features to drop unnecessary features.
3. Train the model using different algorithms  with hyperparameter Tuning.
4.  Evaluate model performance.

**Comment by dona-samir** [comment]
Hi, I am GSSoC'22 contributor ,I have worked with ML models before.
I can do the following

1.do data Analysis & preprocessing if need it .
2.check relation between features to drop unnecessary features.
3.Train the model using linear_model.SGDRegressor algorithms with hyperparameter Tuning.
4.Evaluate model performance.

**Comment by mo1998** [comment]
Hi, i am GSSoC'22 contributor and i would like to work on this issue if not assigned yet.
I have been worked on similar projects.

**Comment by Rutikab12** [comment]
assigned @ADITYADAS1999

**Comment by Rutikab12** [comment]
@ADITYADAS1999  What's the update on your model?

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 What's the update on your model?

The code is ready run successfully, after getting some changes in format i make the PR.
