### ISSUE TITLE
Cryotherapy Analysis

### ISSUE THREAD

**Issue by Rutikab12** [Niketkumardheeryan/ML-CaPsule#257]
## Dataset:
- Cryotherapy is a treatment where your healthcare provider applies extreme cold to freeze and destroy abnormal tissue. To create this severe cold, your provider will use a substance like liquid nitrogen or argon gas.
- Cryotherapy can be used to treat a variety of skin conditions and some cancers, including prostate and liver cancer. This therapy can treat tissue externally (on the skin) and internally (inside the body).

## Dataset:
https://www.kaggle.com/mmkvarma/cryotherapy-analysis

**Comment by yashh18** [comment]
I can do this if you can explain the approach on how to do it

**Comment by dona-samir** [comment]
Hi, I am GSSoC'22 contributor ,I have worked with ML models before.
I can do the following
1.do data Analysis & preprocessing if need it .
2.check relation between features to drop unnecessary features.
3.Train the model using different algorithms with hyperparameter Tuning.
4.Evaluate model performance.

**Comment by mo1998** [comment]
Hi, i am GSSoC'22 contributor and i would like to work on this issue if not assigned yet.
I have been worked on similar projects.
