### ISSUE TITLE
Fish Weight Prediction

### ISSUE THREAD

**Issue by Rutikab12** [Niketkumardheeryan/ML-CaPsule#258]
## Description:
- predict the weight of the any fish

## Dataset:

https://www.kaggle.com/aungpyaeap/fish-market

**Comment by shivam-s16** [comment]
Sir I am interested in this work in GSSoC'22.Could you please assign this to me.

**Comment by Rutikab12** [comment]
@shivam-s16 assigned.

**Comment by shivam-s16** [comment]
@Rutikab12 please assign level to this so that I can get point on leaderboard .
