### ISSUE TITLE
IMDB Box Office Prediction

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#264]

**Comment by dona-samir** [comment]
Good Morning, I'm a GSSOC'22 participant, 
May I know details about the project please?

**Comment by pratishthaa** [comment]
Afternoon @dona-samir , you have to do box office revenue collection prediction, you have to do ML to present the best model. Please make sure to go through with all processes(data preprocessing to modes)

**Comment by pratishthaa** [comment]
@dona-samir comment if you want to work on this issue.

**Comment by dona-samir** [comment]
I am very interested to contribute in this issue, Would you please provide me with the dataset, and the details required?

**Comment by pratishthaa** [comment]
https://www.kaggle.com/c/box-office-revenue-prediction
@dona-samir you can use this dataset

**Comment by SoumyoNathTripathy** [comment]
I am very interested to contribute in this issue, please assign this repo so that  I can start working ASAP

**Comment by WhiteWolf47** [comment]
@pratishthaa i would really like to work on this issue, can u assign it to me
