### ISSUE TITLE
Sentiment analysis for depression based on social media post

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#265]

**Comment by 0ddoes** [comment]
Hello SIr, I am Izza. If this issue is open please assign it for me as part of GSSoC. Will there be a dataset that I can work on?

**Comment by pratishthaa** [comment]
You can look for the dataset on Kaggle. I am sure you can find it there, still, if you have any issues, leave a comment.

**Comment by 0ddoes** [comment]
Hello, I made a pull request with the right file now. Please check again.
