### ISSUE TITLE
Fake News Detection with two Different ML Model other then Logistic Regression.

### ISSUE THREAD

**Issue by srajan-kiyotaka** [Niketkumardheeryan/ML-CaPsule#273]
I have used different models in NLP and made models similar to this in past with an accuracy of 95%+,
I will use two different ML models which are effective in these kinds of datasets.

**Comment by srajan-kiyotaka** [comment]
Hii!
I am a participant in GSSOC'22. Please assign me this issue.

**Comment by pratishthaa** [comment]
This is a very basic NLP project.
