### ISSUE TITLE
German traffic sign recognition benchmark Model

### ISSUE THREAD

**Issue by Rutikab12** [Niketkumardheeryan/ML-CaPsule#293]
## Dataset

- https://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset

**Comment by Bhawna-Ad** [comment]
Hey! I would like to work on this issue. Can you please assign this issue to me under GSSoC'22?

**Comment by Rutikab12** [comment]
Make PR till 31 May.

**Comment by Bhawna-Ad** [comment]
Sure. Thanks!

**Comment by Bhawna-Ad** [comment]
Hey! I have created the pull request. Could you please take a look?

**Comment by Bhawna-Ad** [comment]
@Rutikab12 I have added another commit to the PR for this issue. Can you check that one? I think it should work now.
