### ISSUE TITLE
Number of People Counter Project

### ISSUE THREAD

**Issue by Rutikab12** [Niketkumardheeryan/ML-CaPsule#294]
## Description:

- You have to do is detect whether the frame contains a human being or not and then increase the counter for each unique human being the system detects. 
- For this project, you should explore libraries like NumPy, OpenCV, dlib, and imutils.

**Comment by kashish0505kashyap** [comment]
I have good knowledge and experience with python libraries like OpenCV and numpy. I would like to work on this project.

**Comment by Rutikab12** [comment]
> I have good knowledge and experience with python libraries like OpenCV and numpy. I would like to work on this project.

Assigned @kashish0505kashyap .
