### ISSUE TITLE
Bidirectional LSTM from beginning

### ISSUE THREAD

**Issue by pratishthaa** [Niketkumardheeryan/ML-CaPsule#300]

**Comment by shreya024** [comment]
@Rutikab12 @Niketkumardheeryan I would like to work on this issue. Kindly assign. Also any specific dataset I need to use for this?

**Comment by Rutikab12** [comment]
> @Rutikab12 @Niketkumardheeryan I would like to work on this issue. Kindly assign. Also any specific dataset I need to use for this?

You can use any suitable dataset for the same.
