### ISSUE TITLE
Credit Card Fraud Detection

### ISSUE THREAD

**Issue by aka9ksha** [Niketkumardheeryan/ML-CaPsule#311]
Credit Card Fraud Detection using machine learning.

**Comment by aka9ksha** [comment]
GSSOC Participant .
I would like to work on this issue.

**Comment by Rutikab12** [comment]
Hey, @aka9ksha  can you try to work on a little bit different issue, as it is very common.

**Comment by aka9ksha** [comment]
Alright! :)
