### ISSUE TITLE
Free clouds for hosting Machine learning models 

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#322]

**Comment by Pushpita05** [comment]
Hey I would like to work on this, could you assign me for gssoc 22

**Comment by Pushpita05** [comment]
Hey can you explain in detail, what should I do

**Comment by Niketkumardheeryan** [comment]
> Hey can you explain in detail, what should I do

Add doc file or create a readme.md file and listed the different clouds with a brief explanation

**Comment by Pushpita05** [comment]
Great thanks

**Comment by Pushpita05** [comment]
What is the deadline? @Niketkumardheeryan

**Comment by Pushpita05** [comment]
@Niketkumardheeryan  I have created a PR. Pls check

**Comment by Pushpita05** [comment]
@Niketkumardheeryan pls check. It has been 5days

**Comment by Pushpita05** [comment]
@Niketkumardheeryan pls close this issue as pr is merged
