### ISSUE TITLE
Bird Species Claassificatin & model deployment

### ISSUE THREAD

**Issue by pratishthaa** [Niketkumardheeryan/ML-CaPsule#355]
https://www.kaggle.com/datasets/gpiosenka/100-bird-species

**Comment by shreya024** [comment]
Hi, I am Shreya, a GSSOC'22 contributor,I would like to work on this issue.

**Comment by shreya024** [comment]
Hey @pratishthaa , I have created the model https://www.kaggle.com/code/shreyaghosh24/ml-capsule-bird.Kindly review and guide me through the next steps like which directory to add this to and how to deploy using streamlit.Thank you.

**Comment by pratishthaa** [comment]
Leave comments in your code and for deployment, there are many youtube videos on that, and when you are done , make a PR with Readme and demo video of model

**Comment by heymansi** [comment]
Heyy!
I am GSSoC'22 contributor.
Please assign me this issue

**Comment by heymansi** [comment]
Does this mean this issue is assigned to me??
