### ISSUE TITLE
Add Word cloud @GSSOC'22 

### ISSUE THREAD

**Issue by mohanadtalat91** [Niketkumardheeryan/ML-CaPsule#361]
### Adding Word Cloud Project.

**Description**

Word Cloud or Tag Clouds is a visualization technique for texts that are natively used for visualizing the tags or keywords from the websites. These keywords typically are single words that depict the context of the webpage the word cloud is being made from. These words are clustered together to form a Word Cloud.

Each word in this cloud has a variable font size and color tone. Thus, this representation helps to determine words of prominence. A bigger font size of a word portrays its prominence more relative to other words in the cluster. Word Cloud can be built in varying shapes and sizes based on the creators’ vision. The number of words plays an important role while creating a Word Cloud. More number of words does not always mean a better Word Cloud as it becomes cluttery and difficult to read. A Word Cloud must always be semantically meaningful and must represent what it is meant for.

**Comment by Rutikab12** [comment]
@mohanadtalat91 assigned. You have made a PR , right?

**Comment by mohanadtalat91** [comment]
> @mohanadtalat91 assigned. You have made a PR , right?

Yup, but I'll add README file for this specific project at the same pr as much as possible.

**Comment by Rutikab12** [comment]
> > @mohanadtalat91 assigned. You have made a PR , right?
> 
> Yup, but I'll add README file for this specific project at the same pr as much as possible.

do it as early as possible

**Comment by mohanadtalat91** [comment]
You closed this issue, but you maybe forgot to merge the according PR #359  ??!

@Niketkumardheeryan
