### ISSUE TITLE
Spelling corrector and deploy model

### ISSUE THREAD

**Issue by pratishthaa** [Niketkumardheeryan/ML-CaPsule#365]
https://www.kaggle.com/datasets/bittlingmayer/spelling

**Comment by shreya024** [comment]
@pratishthaa I would like to work on this issue.Kindly assign

**Comment by AkritiAgarwal09** [comment]
Hi @pratishthaa 
I want to take up this issue

**Comment by pratishthaa** [comment]
@shreya024 How much time do u need for this(max time is 6 days)?

**Comment by shreya024** [comment]
> @shreya024 How much time do u need for this(max time is 6 days)?

I will make a PR within 3-4 days
