### ISSUE TITLE
House Price Prediction

### ISSUE THREAD

**Issue by Shweta2024** [Niketkumardheeryan/ML-CaPsule#374]
Hello! I'm a GSSoC'22 contributor. I would like to contribute to this repository by making a project for Predicting the House Prices using Linear Regression. Please assign me this issue.

**Comment by Rutikab12** [comment]
> Hello! I'm a GSSoC'22 contributor. I would like to contribute to this repository by making a project for Predicting the House Prices using Linear Regression. Please assign me this issue.


hey @Shweta2024 Please choose other open issues.
