### ISSUE TITLE
Classify tweets

### ISSUE THREAD

**Issue by pratishthaa** [Niketkumardheeryan/ML-CaPsule#376]
https://www.kaggle.com/datasets/nikhiljohnk/tweets-with-sarcasm-and-irony

**Comment by Shweta2024** [comment]
Hello! I am a GSSoC'22 Contributor. I would like to contribute to this task using Logistic Regression. Please assign this task to me.
Thank you!

**Comment by Shweta2024** [comment]
Hello! I am a GSSoC'22 Contributor. I would like to contribute to this task using Logistic Regression. Please assign this task to me.
Thank you!

**Comment by mgncodes** [comment]
Hi, I would like to contribute to this task as part of GSSoC'22. Kindly assign me this issue. Thanks!

**Comment by rohitpadage** [comment]
I have a good understanding of classification. 
I would like to work on this issue.
Please assign the issue.

**Comment by Rutikab12** [comment]
> I have a good understanding of classification. I would like to work on this issue. Please assign the issue.

Hey would you like to work on this issue?

**Comment by Neha-Niharika-Kar** [comment]
Hello, can I work on this issue?

**Comment by Neha-Niharika-Kar** [comment]
Can you assign me this issue? I'm a GSSoC'22 contributor.

**Comment by Neha-Niharika-Kar** [comment]
Hello, should I create a PR?

**Comment by Neha-Niharika-Kar** [comment]
Please review my PR

**Comment by nkhanna94** [comment]
Hi @pratishthaa,

I'm really excited about the project and would love to be a part of it. Drawing from my experience with similar projects in the past, I'm confident that I can bring valuable insights and contribute effectively. If possible, I'd appreciate being assigned to the project. Looking forward to your response. Thank you!

**Comment by nkhanna94** [comment]
Hi @pratishthaa,

I'm really excited about the project and would love to be a part of it. Drawing from my experience with similar projects in the past, I'm confident that I can bring valuable insights and contribute effectively. If possible, I'd appreciate being assigned to the project. Looking forward to your response. Thank you!

**Comment by pratishthaa** [comment]
Closed
