### ISSUE TITLE
Skin Disease Predictor Using Deep Learning

### ISSUE THREAD

**Issue by srajan-kiyotaka** [Niketkumardheeryan/ML-CaPsule#387]
I will use the Image Dataset of skin Disease to train the CNN Model.

**Comment by srajan-kiyotaka** [comment]
Hii!
I am a participant in GSSOC'22. Please assign me this issue.

**Comment by shreya024** [comment]
@Rutikab12 I would like to work on this issue. Kindly assign

**Comment by Rutikab12** [comment]
@shreya024 go for it.
