### ISSUE TITLE
CrowdAI Plant Disease Prediction Using Deep Neural Network

### ISSUE THREAD

**Issue by srajan-kiyotaka** [Niketkumardheeryan/ML-CaPsule#395]
I will use the image dataset to train the CNN Model,
To predict the CrowdAI Plant Disease.

**Comment by srajan-kiyotaka** [comment]
Hii!
I am a participant in GSSOC'22. Please assign me this issue.

**Comment by heymansi** [comment]
I am contributor in GSSoC'22. Please assign me this issue
