### ISSUE TITLE
Alzheimers Disease Prediction using Deep Neural Network

### ISSUE THREAD

**Issue by srajan-kiyotaka** [Niketkumardheeryan/ML-CaPsule#396]
I will use the CG Scan of the brain image dataset to
train the CNN Model to predict the Alzheimers Disease.

**Comment by srajan-kiyotaka** [comment]
Hii!
I am a participant in GSSOC'22. Please assign me this issue.

**Comment by heymansi** [comment]
Hey!
I am GSSoC'22 contributor. 
Would love to work on CNN model.
Please assign me this issue
Thank you!
