### ISSUE TITLE
Integrate  a ML/  DL  model with Android app

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/ML-CaPsule#402]

**Comment by kashish0505kashyap** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by Rutikab12** [comment]
> I would like to work on this issue. Can you please assign this to me? @Niketkumardheeryan @Rutikab12

only 2 days for making a PR. Please do as early as possible.
