### ISSUE TITLE
To remove Keyframes and Perform Object Detection on Keyframes

### ISSUE THREAD

**Issue by omkar806** [Niketkumardheeryan/ML-CaPsule#403]
Description : So in this project made by me I will remove keyframes from any video and then also I will save each keyframe with its time stamp in a particualr folder and then also I will be performing object detection using the YOLO V3 model for each key frame that I have extracted from the video

**Comment by omkar806** [comment]
please assign this issue to me

**Comment by Rutikab12** [comment]
> please assign this issue to me

@omkar806 Please write the description in description not in the heading of the Issue. Please refer other issues for the same. and get assigned.

**Comment by omkar806** [comment]
I have Updated the Issue and also written the description please assign the issue to me .

**Comment by Rutikab12** [comment]
@omkar806 go for it.

**Comment by Rutikab12** [comment]
> @Rutikab12 hey can i work on this issue as i have done a similar project before. Thankyou

Already PR has been made on this issue. You can look for other open issues. Thanks.
