### ISSUE TITLE
Animal Classification and model deployment

### ISSUE THREAD

**Issue by pratishthaa** [Niketkumardheeryan/ML-CaPsule#407]
https://www.kaggle.com/datasets/ayushv322/animal-classification

**Comment by srajan-kiyotaka** [comment]
@pratishthaa 
I would like to work on this issue. Kindly assign

**Comment by Niketkumardheeryan** [comment]
> Hii, I am GSSOC'22 contributor @pratishthaa could you please assign me this issue ?

go for it
