### ISSUE TITLE
Backpropagation Intuition for Regression and Classification 

### ISSUE THREAD

**Issue by AyushJain001** [Niketkumardheeryan/ML-CaPsule#417]
I will demonstrate the intuition behind the working of backpropagation using self code and inbuilt Keras library.

**Comment by AyushJain001** [comment]
Kindly assign this issue under GSSOC'22. I would like to work on that.

**Comment by Rutikab12** [comment]
@AyushJain001 PLease look for other open Issues.  Thanks.
