### ISSUE TITLE
Duplicate Question Pair End to End NLP Project 

### ISSUE THREAD

**Issue by pawansharma197** [Niketkumardheeryan/ML-CaPsule#419]

**Comment by pawansharma197** [comment]
Hello Myself Pawan Sharma GSSOC"22 plz assign this issue to me .

**Comment by Rutikab12** [comment]
Go for it @pawansharma197

**Comment by heymansi** [comment]
Hii
I am GSSOC'22 contributor,
could you please assign me this issue?

**Comment by Rutikab12** [comment]
> Hii I am GSSOC'22 contributor, could you please assign me this issue?

Already Assigned. Please look for other open issues. Thanks.

**Comment by pawansharma197** [comment]
Made a Pull Request . Please Review it
