### ISSUE TITLE
Github Topic Scraper

### ISSUE THREAD

**Issue by aritra1804** [Niketkumardheeryan/ML-CaPsule#422]
I would like to wok on a web scraper that would help beginners or in general developers to find repositories based on what topic they are interested. Pls assign me this issue for gssoc 22

**Comment by aritra1804** [comment]
@Rutikab12 Could you please add the gssoc 22 and level1,2,3 label in my previous Merged PR , Else it won't be counted. 
This is the link of my previous PR https://github.com/Niketkumardheeryan/ML-CaPsule/pull/288

**Comment by Rutikab12** [comment]
> @Rutikab12 Could you please add the gssoc 22 and level1,2,3 label in my previous Merged PR , Else it won't be counted. This is the link of my previous PR #288

Done.
