### ISSUE TITLE
Fake news detection using the text + title  column #GSSOC'22

### ISSUE THREAD

**Issue by hemhemoh** [Niketkumardheeryan/ML-CaPsule#433]
Hello, I am a GSSOC'22 participant and I'd love to build a fake news detector using the text and title column as opposed the author and title that was used previously

**Comment by Niketkumardheeryan** [comment]
@hemhemoh its already there

**Comment by hemhemoh** [comment]
@Niketkumardheeryan For the one that is there, it is the title and author column that was used, I want to use the text and title column now.
