### ISSUE TITLE
Cheat Sheets 

### ISSUE THREAD

**Issue by subhadeeppaul** [Niketkumardheeryan/ML-CaPsule#445]
Add a complete cheatsheet on  Numpy, Pandas, Seaborn and Matplotlib in the Cheat Sheets section.

**Comment by Tanuj-rai** [comment]
Can you please assign me this issue?

**Comment by Rutikab12** [comment]
> Can you please assign me this issue?

@Tanuj-rai have you made a PR?

**Comment by Tanuj-rai** [comment]
Not now because of exams I couldn't not make. I will make PR, give me 1 or
2 days.

**Comment by Rishi2003Das** [comment]
Hi I am Rishi. I am selected for GSSOC'24. Is this issue still open then I want to work..?

**Comment by tejaswi-c** [comment]
Hello
I am a contributor of GSSoC'24
I'd like to contribute, kindly assign me this issue.

**Comment by shreyasadhasivam** [comment]
I would like to work on this issue. Please assign it to me

**Comment by subhadeeppaul** [comment]
Hello everyone! I apologize, but the issue has been resolved and is now closed.
