### ISSUE TITLE
Predicting Student Performance 

### ISSUE THREAD

**Issue by prinks-wiz** [Niketkumardheeryan/ML-CaPsule#463]
Hi! I am a GSSoC '22 participant. I would like to use SVM regression technique to predict student performance. Kindly assign this issue to me.

**Comment by Rutikab12** [comment]
> Hi! I am a GSSoC '22 participant. I would like to use SVM regression technique to predict student performance. Kindly assign this issue to me.

which dataset you are using. Please share .

**Comment by prinks-wiz** [comment]
https://www.kaggle.com/datasets/yasserh/student-marks-dataset

**Comment by Rutikab12** [comment]
> https://www.kaggle.com/datasets/yasserh/student-marks-dataset

Okay. You can work on it.

**Comment by Niketkumardheeryan** [comment]
> https://www.kaggle.com/datasets/yasserh/student-marks-dataset

sorry you can create another issue,bcz we are not accepting simple predictions
