### ISSUE TITLE
Data cleaning and sentiment analysis on restaurant data

### ISSUE THREAD

**Issue by hemhemoh** [Niketkumardheeryan/ML-CaPsule#481]
Hi, I would like to clean and perform sentiment analysis on the reviews of a particular restaurant known as Zomato Restaurant. Kindly assign to me #GSSOC22.

**Comment by Rutikab12** [comment]
> Hi, I would like to clean and perform sentiment analysis on the reviews of a particular restaurant known as Zomato Restaurant. Kindly assign to me #GSSOC22.

Please look for other open issues. Thanks.
