### ISSUE TITLE
Fire Detection using python and Open CV

### ISSUE THREAD

**Issue by subhadeeppaul** [Niketkumardheeryan/ML-CaPsule#484]

**Comment by urvisinghal** [comment]
Can you assign this to me please

**Comment by subhadeeppaul** [comment]
Go for it

**Comment by chandan2300** [comment]
Hi @subhadeeppaul is this issue still open?

**Comment by subhadeeppaul** [comment]
Yes

**Comment by OmChillure** [comment]
@subhadeeppaul Can you please assign this issue to me under GSSoc'24 !

**Comment by shrehs** [comment]
hey @subhadeeppaul,
I would love to work on this issue. I believe I could contribute on this issue. I have worked on ML projects before. Please let me know if you could assign this issue to me. Thank you.

**Comment by ShreyaAwasekar** [comment]
@subhadeeppaul can you this to me under GSSoc' 24  I have worked on similar types of projects before.

**Comment by chandan2300** [comment]
Guys, this has been merged already - https://github.com/Niketkumardheeryan/ML-CaPsule/pull/520

**Comment by Hireath08** [comment]
Hi @subhadeeppaul is this issue still open?

**Comment by Sounakray2003** [comment]
hey @subhadeeppaul,
I would love to work on this issue. I believe I could contribute on this issue. I have worked on ML projects before. Please let me know if you could assign this issue to me. Thank you.

**Comment by Hireath08** [comment]
hi @chandan2300 I would love to work on this issue.  Please let me know if you could assign this issue to me. Thank you.

**Comment by saisri0102** [comment]
I am GSoc24 contributor
Can you assign me this issue?

**Comment by hit-haa18** [comment]
@subhadeeppaul Is this issue still open?
If yes could you please assign this to me under GSSOC'24

**Comment by Pranali3103** [comment]
@subhadeeppaul Can you please assign me this issue !! I would like to work upon this .

**Comment by arun0r7** [comment]
@subhadeeppaul  Can you please assign this issue to me so that I can contribute here. Would like to work upon this one.

**Comment by subhadeeppaul** [comment]
Hello everyone! I apologize, but the issue has been resolved and is now closed.
