### ISSUE TITLE
Sentiment Analysis of IMDb movie reviews

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [Niketkumardheeryan/ML-CaPsule#488]
1. Fetching movie reviews using IMDb API based on user input. 
2. Using different sentiment analysis libraries such as textblob, text2emotion, nltk, flair to analyze sentiments and produce result in form of text and graphs.

End project - Jupyter ntbk.

**Comment by Rutikab12** [comment]
> 1. Fetching movie reviews using IMDb API based on user input.
> 2. Using different sentiment analysis libraries such as textblob, text2emotion, nltk, flair to analyze sentiments and produce result in form of text and graphs.
> 
> End project - Jupyter ntbk.

Go for it. Make a PR within 5 days.
