### ISSUE TITLE
Heart Disease Prediction 

### ISSUE THREAD

**Issue by TANYA-CHAN** [Niketkumardheeryan/ML-CaPsule#497]
I would like to add a project which is a Heart Disease Predictor and uses multiple ML Algorithms like: 
Logistic Regression 
Naive Bayes 
Support Vector Machine 
K-Nearest Neighbors 
Decision Tree 
Random Forest 
XGBoost
Neural Network

**Comment by TANYA-CHAN** [comment]
can you please assign it to me?

**Comment by Rutikab12** [comment]
Hey, @TANYA-CHAN if you want I can assign you issue number #451  Instead of this issue. Have a look.

**Comment by TANYA-CHAN** [comment]
@Rutikab12 I already have done this project and tested it, that's why it's easier to edit and contribute, please understand as my final exams are going on.

**Comment by Rutikab12** [comment]
> @Rutikab12 I already have done this project and tested it, that's why it's easier to edit and contribute, please understand as my final exams are going on.

Excuse me , but I can't as it is already done.

**Comment by TANYA-CHAN** [comment]
Okay cool, thank you.

> > @Rutikab12 I already have done this project and tested it, that's why it's easier to edit and contribute, please understand as my final exams are going on.
> 
> Excuse me , but I can't as it is already done.
