### ISSUE TITLE
Song genre classifier using NLP

### ISSUE THREAD

**Issue by TANYA-CHAN** [Niketkumardheeryan/ML-CaPsule#498]
1. This project aims to identify which genre a song belongs to on the basis of its lyrics
2. The dataset contains 62155 songs
3. Each song is classified into 5 genres- Country, Rock, Hip-Hop, Pop and Rhythm and Blues
4. Two major text classification methods were tested- Logistic Regression and Naïve Bayes
5. Under Naïve Bayes, 3 models were tested- Count Vectorizer, TF-IDF, and Text Cleaning
6. Upon testing, Multinomial Naïve Bayes with Text Cleaning was found to give the highest accuracy
7. Further analysis was also done to find top songs and generate WordClouds

I'll be implemented using Jupyter Notebook

**Comment by TANYA-CHAN** [comment]
@Rutikab12 is this okay?

**Comment by Rutikab12** [comment]
> @Rutikab12 is this okay?

Yeah. Go for it

**Comment by TANYA-CHAN** [comment]
![2022-05-21 (64)](https://user-images.githubusercontent.com/57089030/169658624-3a3ab0e2-56b9-4362-b764-69fa3429937b.png)
@Rutikab12  what does this error specify?

**Comment by Rutikab12** [comment]
Try to relogin to your account. Change github password. LAst login session might have been stopped.

**Comment by Rutikab12** [comment]
> ![2022-05-21 (64)](https://user-images.githubusercontent.com/57089030/169658624-3a3ab0e2-56b9-4362-b764-69fa3429937b.png) @Rutikab12 what does this error specify?

[You can also take help of this link](https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed)

**Comment by TANYA-CHAN** [comment]
> > ![2022-05-21 (64)](https://user-images.githubusercontent.com/57089030/169658624-3a3ab0e2-56b9-4362-b764-69fa3429937b.png) @Rutikab12 what does this error specify?
> 
> [You can also take help of this link](https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed)

Done I've created the PR, thank you so much.

**Comment by TANYA-CHAN** [comment]
@Rutikab12
![2022-05-21 (106)](https://user-images.githubusercontent.com/57089030/169662648-7a3d73fd-7eae-4db1-ad24-f7b419a74642.png)
How do I add the .csv because it is too large

**Comment by Rutikab12** [comment]
> @Rutikab12 ![2022-05-21 (106)](https://user-images.githubusercontent.com/57089030/169662648-7a3d73fd-7eae-4db1-ad24-f7b419a74642.png) How do I add the .csv because it is too large

Just post link of it, if its from kaggle . PRefer to use Github desktop, it is quite handy in terms of use.

**Comment by TANYA-CHAN** [comment]
@Rutikab12 please tell me the status of this project sir
