### ISSUE TITLE
Complete EDA, Feature enginering  and Feature selection on BackOrder Dataset

### ISSUE THREAD

**Issue by umangtank** [Niketkumardheeryan/ML-CaPsule#505]
EDA and Feature Engineering is very important task of any data science project which is take almost 70% time of any end to end Data science project.

**Comment by umangtank** [comment]
@Niketkumardheeryan please asign me

**Comment by Rutikab12** [comment]
> @Niketkumardheeryan please asign me

@umangtank Please look for other open issues. Thanks.
