### ISSUE TITLE
Pneumonia Classification using Chest X-Ray 

### ISSUE THREAD

**Issue by Subhranil2004** [Niketkumardheeryan/ML-CaPsule#534]
**Overview** :
The aim is to develop a predictive model for classifying Chest X-ray images as pneumonia-affected or not.
Classes:
- Normal
- Pneumonia
     - Bacterial [ Future scope ]
     - Viral       [ Future scope ]

**Objective** : 
The primary objective of this project is to create a deep learning (CNN) model that can accurately predict which class of Pneumonia a chest X-ray image belongs to. 

I would like this issue to be assigned to me as part of GSSoC'24 with the `gssoc` label and the appropriate `level (1/2/3)`.
Thank you.

**Comment by ishaanv1206** [comment]
Hi @Subhranil2004 
Please assign the issue to me i have previously worked on similar datasets like tumor detection and Alzheimer prediction
I will create a web app for it too

**Comment by Piyushseth55** [comment]
Hii, I am Piyush. Under GSSOC'24, I would like to work on this issue. Pls assign me this!! #gssoc24

**Comment by diptarup794** [comment]
Hi,I want to work on this issue . I have worked on similar problems before and am confident about dealing with this one as well . Kindly assign it to me @Subhranil2004

**Comment by Subhranil2004** [comment]
Actually, I am a GSSoC contributor, so I cannot assign it to anyone.
I want to work on this issue/project myself. Thus, I opened it.

**Comment by shrehs** [comment]
Hello!
I have worked on two image classifiers- dog breed classifier and flower classifier, I believe I'm able to contribute to the project due to my previouse projects. I have worked with AlexNet, VGG-16 of CNN. If given the oppurtunity I would love to be involved with this project. Please do consider my request. Thank you very much!

**Comment by invigorzz313** [comment]
The issue has been assigned on FCFS basis.
@Subhranil2004 Do follow the project guidelines for PR.

**Comment by Subhranil2004** [comment]
> The issue has been assigned on FCFS basis. @Subhranil2004 Do follow the project guidelines for PR.

Ok I'll follow the guidelines. 
Can you kindly assign the `level (1/2/3)` label as well @invigorzz313

**Comment by invigorzz313** [comment]
The label assigning will be done on the submitted PR after reviewing it.

**Comment by Subhranil2004** [comment]
@invigorzz313 kindly check my pull request and confirm if everything is ok.
