### ISSUE TITLE
Hindi Letter Classification

### ISSUE THREAD

**Issue by ishaanv1206** [Niketkumardheeryan/ML-CaPsule#536]
Predict Devanagari Hindi alphabets into 46 classes based on image using CNN.
will contain following classes: 
ka
kha
ga
gha
kna
cha
chha
ja
jha
yna
tamaatar
thaa
daa
dhaa
adna
tabala
tha
da
dha
na
pa
pha
ba
bha
ma
yaw
ra
la
waw
motosaw
petchiryakha
patalosaw
ha
chhya
tra
gya
0
1
2
3
4
5
6
7
8
9

Will create a web application for it

**Comment by nkhanna94** [comment]
Please consider assigning this project to me. I plan to use CNNs and other machine learning algos to effectively classify Hindi letters.

**Comment by Sgvkamalakar** [comment]
Full name: S G V Kamalakar

GitHub Profile Link: https://github.com/Sgvkamalakar

Email ID: [sgvkamalakar@gmail.com](mailto:sgvkamalakar@gmail.com)

Approach for this Project: The approach involves utilizing a Convolutional Neural Network (CNN), LSTM transform-learning with pre-trained models, and trying hybrid models to accomplish `Hindi` alphabet classification.

I'll submit a PR within the next few days. Would u like to assign issue #536 to me?

**Is there a specific dataset provided for this project, or do I have the option to choose from open-source sites?**
