### ISSUE TITLE
Data Structures in Python 

### ISSUE THREAD

**Issue by Ishita-Jena** [Niketkumardheeryan/ML-CaPsule#555]
I want to add a "Data Structures" folder having linked list, stack, queue, etc. Please assign this issue to me.

**Comment by linga-007** [comment]
I would like to work on this Issue . Kindly assign this to me . Had previous hands on experience on data structures in python .

**Comment by akshaydubey05** [comment]
Hi,i would like to solve this issue please can you assign this issue to me?
Also please add label to it after assigning.

**Comment by invigorzz313** [comment]
This repository is for projects primarily in the domain of Machine Learning or data science.

**Comment by invigorzz313** [comment]
This issue will now be closed.
