### ISSUE TITLE
Adding ipynb files in python lectures

### ISSUE THREAD

**Issue by Varshni11** [Niketkumardheeryan/ML-CaPsule#558]
Hi @Niketkumardheeryan , I can that in the python folder except for basics other lectures are in pdf format. I can create pdfs and ipynb formats for other folders too. Please assign the issue to me

**Comment by Niketkumardheeryan** [comment]
The issue has been assigned to you , Please follow project guidelines for PR.

**Comment by Varshni11** [comment]
Thanks, I will.

**Comment by SuhaniStark** [comment]
please assign me the project i want to work on it

**Comment by Varshni11** [comment]
#709
