### ISSUE TITLE
Fake_News_Detection

### ISSUE THREAD

**Issue by AKing-283** [Niketkumardheeryan/ML-CaPsule#562]
**Integrating Frontend for proper usage and access of the model**
This model is not having frontend as we need to paste the text in the model. so user can access this model and can get thee feedback via the frontend itself.

Please assign me this task for GSSOC'24 contribution I would like to work on it. this issue. @Niketkumardheeryan

**Comment by Niketkumardheeryan** [comment]
The issue has been assigned to you , Please follow project guidelines for PR.

**Comment by AKing-283** [comment]
**Made a PR but facing some errors too**
@Niketkumardheeryan I have made a PR but I am facing an issue of error while I am running the gradio snippet in colab. @invigorzz313 please guide me with this so that I can complete it

**Comment by invigorzz313** [comment]
@AKing-283 Can you tag that PR here?

**Comment by AKing-283** [comment]
#681 here is my pull request @invigorzz313
