### ISSUE TITLE
Movie Genre Classification Prediction

### ISSUE THREAD

**Issue by Manav173** [Niketkumardheeryan/ML-CaPsule#566]
Overview:
This project aims to develop a predictive model for movie genre classification based on various features such as plot summary, cast, crew, and user reviews. This issue tracks the progress and tasks associated with the development of this predictive model.

Objective:
The primary objective of this project is to create a machine learning model that can accurately classify the genre of a movie based on its relevant attributes.

I would like this issue to be assigned to me as part of GSSoC'24. Thank you.

**Comment by Niketkumardheeryan** [comment]
The issue has been assigned to you , Please follow project guidelines for PR. issue assigned BAsed on FCFS
