### ISSUE TITLE
Add to Web-Scraping-with-Beautiful-Soup-master and remove invalid notebooks.

### ISSUE THREAD

**Issue by speckofstardust** [Niketkumardheeryan/ML-CaPsule#592]
There are multiple ipynb files in Web-Scraping-with-Beautiful-Soup-master folder that do not appear to Be Valid JSONs. I would like to remove these files and add programs for extracting data from websites like Wikipedia and Amazon. 
Please assign this issue to me @Niketkumardheeryan .
Additional info for tags: I am participating as contributor through gssoc' 24.

**Comment by Niketkumardheeryan** [comment]
Assigned to you , PLease follow Project guidelines for before making a PR.
