### ISSUE TITLE
Mall customer segmentation using K-means Clustering

### ISSUE THREAD

**Issue by Hannan2004** [Niketkumardheeryan/ML-CaPsule#594]
Hi I am a beginner to machine learning and as I was going through the list of projects the repository contains I thought that using my existing ML skills I can make a project which segments customers based on their similar characteristics, behavior and needs. It is a good project for someone who has just learnt K means clustering algorithm and want to get their hands dirty with some real world project. I would request to please assign me this project

**Comment by Rishukumarsingh12** [comment]
HI @invigorzz313 ,
I have quite good experience with machine learning and sentiment analysis by including both machine learning and NLP techniques. So , If this issue is still open or i could contribute in this project anyhow please let me know .

Thank you.

**Comment by Hannan2004** [comment]
Can you please assign the gssoc level label to this issue
