### ISSUE TITLE
Handwritten character recognition improve accuracy of the model

### ISSUE THREAD

**Issue by shrehs** [Niketkumardheeryan/ML-CaPsule#598]
I want to improve the accuracy rate of the model by refeeding the important features of the data to neural network.
Could you please assign this issue to me. Thank you!

**Comment by invigorzz313** [comment]
There is already a similar project in the repository. You may open an issue if you have any new ideas.

**Comment by shrehs** [comment]
Oh OK, i will close this issue then. Thank you!

**Comment by shrehs** [comment]
Oh OK, i will close this issue then. Thank you!
