### ISSUE TITLE
Poker Hand Prediction

### ISSUE THREAD

**Issue by aviralgarg05** [Niketkumardheeryan/ML-CaPsule#601]
Predict the Poker Hand of a Player using ML model from Previous as well as Present data. I am a GSSOC'24 Contributor. Could you please assign me.

**Comment by invigorzz313** [comment]
The issue has been assigned to you. @aviralgarg05 
Follow the PR guidelines

**Comment by aviralgarg05** [comment]
Hi, where can I find the PR Guidelines?

**Comment by invigorzz313** [comment]
You can go through the CONTRIBUTING_GUIDELINES.md of this repository [Link](https://github.com/Niketkumardheeryan/ML-CaPsule/blob/master/CONTRIBUTING_GUIDELINES.md)

**Comment by arunitasahu** [comment]
@invigorzz313 @Niketkumardheeryan please assign this issue to me.
