### ISSUE TITLE
Loan Repayment Prediction

### ISSUE THREAD

**Issue by aviralgarg05** [Niketkumardheeryan/ML-CaPsule#602]
Predict if a person may repay his loan or not using machine learning. I am a GSSOC'24 Contributor. Could you please assign me.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by invigorzz313** [comment]
This issue is assigned to you @aviralgarg05 
Do follow the project guidelines for PR.
