### ISSUE TITLE
Netflix Data Analysis PowerBi 

### ISSUE THREAD

**Issue by shubhamnakum** [Niketkumardheeryan/ML-CaPsule#644]
I would like to contribute a comprehensive Netflix analysis project using Power BI to this repository. This project involves detailed data analysis and visualization of a Netflix dataset, providing insights into various aspects such as content trends, preferences, and genre analysis, etc.

**Comment by shubhamnakum** [comment]
@Niketkumardheeryan assigin me this issue, i Want to contribute this to the codebase.

**Comment by invigorzz313** [comment]
This issue has been assigned.
Do follow the project guidelines for PR.

**Comment by invigorzz313** [comment]
This issue will now be closed on successful merging of the PR.
