### ISSUE TITLE
Image Captioning

### ISSUE THREAD

**Issue by HazSyl1** [Niketkumardheeryan/ML-CaPsule#658]
I noticed a lack of **image captioning** work in the repository right now. Implementing image captioning using machine learning is a challenging task, but would greatly benefit learners to understanding the concept of  concatenation of two inputs , and more about image processing with nlp.
I'm interested in contributing to this aspect of the project.
 Can you  assign this issue to me?

**Comment by invigorzz313** [comment]
The issue has been assigned.
Do follow the project guidelines for the PR.

**Comment by HazSyl1** [comment]
Hi, I've added the aforementioned and created a pull request. Kindly check it.
