### ISSUE TITLE
Add Diseases Perdiction model which also gives prescriptions 

### ISSUE THREAD

**Issue by Kyouma45** [Niketkumardheeryan/ML-CaPsule#661]
Based on the provided symptoms from the user, our model will predict what disease our user is suffering from and give prescriptions based on that. It can classify the most common diseases and prescribe the most accurate suggestions based on the disease.
Please assign this issue to me @Niketkumardheeryan

**Comment by sanskritiagr** [comment]
I have worked on a similar project in the past and would like to contribute. Please assign it to me.

**Comment by Niketkumardheeryan** [comment]
@Kyouma45 go for it

**Comment by Kyouma45** [comment]
@Niketkumardheeryan sir, sorry to bother you again and again, but I have finished working on this issue and have created a pull request. Please review it.
