### ISSUE TITLE
Readme.md update required

### ISSUE THREAD

**Issue by Meetjain1** [Niketkumardheeryan/ML-CaPsule#699]
small update in readme.md required, I can add some animated emojis in the file , That will look good .
@Niketkumardheeryan assign this issue to me I will update the readme file 
I am working under gssoc

**Comment by Niketkumardheeryan** [comment]
go for it. Ensure to follow Project guidelines.

**Comment by Meetjain1** [comment]
@Niketkumardheeryan have a look on this pr . Thanks
