### ISSUE TITLE
Missing learn.md file

### ISSUE THREAD

**Issue by Meetjain1** [Niketkumardheeryan/ML-CaPsule#700]
Learn.md file is missing in our current repository 
The learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. This file can serve various purposes, such as introducing new users to the project, providing detailed instructions for using the codebase, or offering learning pathways for different topics covered by the repository.

@Niketkumardheeryan assign this issue to me I wil create and add it .
I am working under gssoc

**Comment by Niketkumardheeryan** [comment]
go for it. Ensure to follow Project guidelines.
