### ISSUE TITLE
building a Chatbot

### ISSUE THREAD

**Issue by psyuktha** [Niketkumardheeryan/ML-CaPsule#703]
I would like to add a project for building a chatbot using nlp techniques and gemini api 
this would help to learn chatbot fundamentals and how to build a chatbot for a beginner with llm and RAG

@Niketkumardheeryan  Im a GSSoC 24 contributor, please assign me this issue

**Comment by DebasisX** [comment]
Assign me this issue, I have experience in building chatbot with Gemini API, use can view my project here, https://github.com/DebasisX/DebX. Thank you.
