### ISSUE TITLE
[Project Addition] : Sports Image Classification 

### ISSUE THREAD

**Issue by kyra-09** [Niketkumardheeryan/ML-CaPsule#704]
Aim / Approach :-  1. ) Using various different available network architectures such as Xception , ResNet50 , VGG16  etc. to do catagorical classification for 100 different sports using dataset (mentioned below) .
2.) use data augmentation techniques to improve the accuarcy of models.
3.) Comparing performance and accuracy of models for better understanding.
4.) Perfroming EDA (data analysis) for dataset to understand the structure of data.
5.) Using README file for describing the work I've performed.

Github Id :- https://github.com/kyra-09
Program :- GSSOC-2024 Contributor

**kindly assign me this issue @Niketkumardheeryan**

**Comment by kyra-09** [comment]
@Niketkumardheeryan @invigorzz313 sir/ma'am kindly assign this issue to me so that I can start working on it

**Comment by invigorzz313** [comment]
This issue has been assigned.
Do follow the project guidelines for PR.
