### ISSUE TITLE
Adding Project: Retail Management System in Python

### ISSUE THREAD

**Issue by piyush-poddar** [Niketkumardheeryan/ML-CaPsule#710]
## Project Description
The proposed python project **SHOPIFY - RETAIL MANAGEMENT SYSTEM** is an engineering approach to enhance current retail shop management and customer billing activities. The software works as a self-service product for retail frontline representative while selling the products and generating customer bill at the same time.

**Approach:** I'll implement the software in Python along with Mysql database as well as using mysql.connector to connect with python.

Expected Level: **Level 2**

Please assign me this issue @Niketkumardheeryan. Thanks!!

## A Preview of what the application will look like
**Product and Inventory Management:**

![image](https://github.com/Niketkumardheeryan/ML-CaPsule/assets/143445461/f5c00fed-80b5-4478-b6a5-c2ed83ffb524)

**Bill Generator:**

![image](https://github.com/Niketkumardheeryan/ML-CaPsule/assets/143445461/4483166c-640e-40cb-976c-b635351f3047)

**Comment by invigorzz313** [comment]
@piyush-poddar Please try to highlight the use of ML/DL/Data Science as that is the purpose of this repo.

**Comment by piyush-poddar** [comment]
@invigorzz313 Actually this project does not use ML or Data Science, I saw some projects not using ML so I thought to contribute this. If it is not appropriate for the repo then I can close this issue.
