### ISSUE TITLE
Project Addition: Movie Revenue Prediction Using ML Libraries

### ISSUE THREAD

**Issue by Vikranth3140** [Niketkumardheeryan/ML-CaPsule#725]
Hello @Niketkumardheeryan 

I would like to raise an issue in order to contribute to GSSoC '24.

I want to add Movie Revenue Prediction Using ML Libraries project to this repository.
You can find it [here](https://github.com/Vikranth3140/Movie-Revenue-Prediction).

Kindly assign this to me under GSSoC '24 and provide a suitable level to it accordingly.

**Comment by Srijansarkar17** [comment]
Hey @Niketkumardheeryan I can work on this issue. I have built similar ML projects
