### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by AmrutaJayanti** [Niketkumardheeryan/ML-CaPsule#731]
I would like to add concepts of feature engineering .Please assign me this task under GSSOC'2024

**Comment by invigorzz313** [comment]
There already seems to be related projects in the codebase. What do you want to improve?

**Comment by AmrutaJayanti** [comment]
No I want to include the feature transformation,feature selection,feature extraction,feature construction and their respective methods

**Comment by AmrutaJayanti** [comment]
@invigorzz313 Label tag is not added to my issue.

**Comment by AmrutaJayanti** [comment]
@invigorzz313  A small query . Should I create another directory `Feature-Engineering` and then add my file
