### ISSUE TITLE
Convolutional neural networks (Deep Learning Algorithm)

### ISSUE THREAD

**Issue by ranamanish674zu** [Niketkumardheeryan/ML-CaPsule#825]
we can use cnn for simple task to uderstand and the layers of CNN and we can apply that model over any data.
approach-Deep Learning (CNN)
i want applly CNN in a simple datasest with different layers

**Comment by adityasingh-0803** [comment]
we can apply deep learning please assign the task

**Comment by ranamanish674zu** [comment]
@Niketkumardheeryan sir could you chake this issue if it is fine then assign it, i want to work on it.
