### ISSUE TITLE
Feed-forward neural networks (Deep Learning Algorithm)

### ISSUE THREAD

**Issue by ranamanish674zu** [Niketkumardheeryan/ML-CaPsule#826]
Can you assign it to me? @Niketkumardheeryan 
Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: [manish.rana2021@vitbhopal.ac.inn](mailto:manish.rana2021@vitbhopal.ac.inn)
Approach for this : Will use Deep Learning and python
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

**Comment by vishalmaurya850** [comment]
Please Add label
