### ISSUE TITLE
Personality prediction system using ML

### ISSUE THREAD

**Issue by ashis2004** [Niketkumardheeryan/ML-CaPsule#861]
objective: Personality prediction system using machine learning (ML) is to accurately infer individuals' personality traits based on various data inputs, such as social media activity, text analysis, and behavioral patterns. The approach involves collecting and preprocessing relevant data to ensure it is clean and structured. This data is then used to train ML models, often utilizing natural language processing (NLP) techniques for text data. Feature extraction methods are employed to identify significant indicators of personality traits. 
Common classification algorithms include decision trees, support vector machines.....

Can you assign it to me? @Niketkumardheeryan
Full Name- Ashish Kumar Patel
GitHub profile link: https://github.com/ashis2004
Email ID: [ashish_kumar2021@vitbhopal.ac.in](mailto:ashish_kumar2021@vitbhopal.ac.in)

What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it

**Comment by invigorzz313** [comment]
@ashis2004 Please do describe the objective.

**Comment by ashis2004** [comment]
pls check it @invigorzz313  once and assign to me

**Comment by invigorzz313** [comment]
The issue has been assigned
