### ISSUE TITLE
Chronic-Kidney-Disease-Prediction-using-ANN-with-Normalization

### ISSUE THREAD

**Issue by pavitraag** [Niketkumardheeryan/ML-CaPsule#884]
This work aims to accurately predict Chronic Kidney Disease (CKD) using a robust Artificial Neural Network model and compares its performance to various machine learning algorithms, ultimately achieving an impressive accuracy of 98%, making it a promising tool for CKD diagnosis.

**Comment by pavitraag** [comment]
@Niketkumardheeryan can u please assign this to me

**Comment by invigorzz313** [comment]
@pavitraag the issue has been assigned.
