### ISSUE TITLE
Customer Segmentation Using Unsupervised Algorithm

### ISSUE THREAD

**Issue by ashis2004** [Niketkumardheeryan/ML-CaPsule#886]
Description- Grouping the customer based on their likes and dislikes on particular product using k-means clustering, DB-scan....algorithm.
Use Case-
A marketing team wants to segment customers based on their purchasing behavior for targeted marketing campaigns, Customer Lifetime Value (CLV) Analysis, Geographical Segmentation ....

![image](https://github.com/Niketkumardheeryan/ML-CaPsule/assets/110098153/8d7a1b3a-6900-4f9d-827b-a1de1987dd60)
Can you assign it to me? @Niketkumardheeryan
Full Name- Ashish Kumar Patel
GitHub profile link: https://github.com/ashis2004
Email ID: [ashish_kumar2021@vitbhopal.ac.in](mailto:ashish_kumar2021@vitbhopal.ac.in)

What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it.

**Comment by invigorzz313** [comment]
@ashis2004 the issue has been assigned.
