### ISSUE TITLE
Employee Attrition prediction using Machine learning

### ISSUE THREAD

**Issue by RajKhanke** [Niketkumardheeryan/ML-CaPsule#899]
This project or feature aims to predict the attrition or sadness in the employees of different companies using machine learning techniques based on given Kaggle dataset :-

https://www.kaggle.com/datasets/mrsimple07/employee-attrition-data-prediction

i will dop a complete data analysis , perform EDA ,processing ,feature extraction and engineering , train different 4-5 machine learning models and select the one with the optimum performance , fine tune the model for correct prediction , draw appropriate conclusion and results as well as trends from data.

i will develop an application based on Streamlit for prediction and  on that app plot my tends , analysis in the form of graphs and stats as well as plot recent news related to employees fired or leaving companies and their effects

**Comment by RajKhanke** [comment]
@invigorzz313 please assign it to me along with level and label of gssoc'24, i have already searched for it in repo and not found this feature

**Comment by invigorzz313** [comment]
@RajKhanke the issue has been assigned.

**Comment by RajKhanke** [comment]
@invigorzz313  please assign level or it will be assigned  based on quality of PR ?
