### ISSUE TITLE
Analyze Molecular Structures using GNN

### ISSUE THREAD

**Issue by aishikaranjan** [Niketkumardheeryan/ML-CaPsule#911]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description
The main goal is to implement a Graph Neural Network (GNN) for predicting molecular properties by utilizing r-radius subgraphs for enhanced molecular representation.
### Use Case
It can be used to predict drug efficacy and photovoltaic efficiency, aiding in drug discovery and material science research by leveraging molecular fingerprint representations.

### Priority
High

### Record
 

- [x] I have read the Contributing Guidelines
- [x]  I'm a GSSOC'24 contributor
- [x]  I want to work on this issue

**Comment by aishikaranjan** [comment]
Kindly assign this issue to me.

**Comment by invigorzz313** [comment]
@aishikaranjan the issue has been assigned.
