### ISSUE TITLE
Heatmap Visualization of a Image Classification Model like Xception using GRAD-CAM

### ISSUE THREAD

**Issue by AMS003010** [Niketkumardheeryan/ML-CaPsule#933]
## What is the Xception model

The Xception model, short for "Extreme Inception," is a deep convolutional neural network architecture. Xception builds upon the Inception architecture but replaces the standard Inception modules with depthwise separable convolutions.

## What is GRAD-CAM
GRAD-CAM, which stands for Gradient-weighted Class Activation Mapping, is a technique used in the field of computer vision to visualize the regions of an image that are important for a convolutional neural network's decision-making process.

## My Proposal
So I would like to use Deep learning techniques like GRAD-CAM to explain why the Xception model is classifying that as an "Persian cat" ( Or anything else ) visually through a heatmap.

## Use Case
Since ML techniques like CNN are essentially "Black Boxes", it is hard for us to understand why it made that choice. Using GRAD-CAM we are able to explain why the CNN model made that particular choice that it did. It helps us to visually understand the "why" of the classification.

## Screenshots

Before sending it as an input to the GRAD-CAM Extractor
![image](https://github.com/user-attachments/assets/799e3392-1581-4f34-b527-45e4cdea087d)

After sending it as an input to the GRAD-CAM Extractor
![image](https://github.com/user-attachments/assets/af512e89-b79f-490f-be62-6d45149a22f6)

## Additional Points
- [x] I have read the Contributing Guidelines
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by invigorzz313** [comment]
@AMS003010 the issue is assigned.

**Comment by AMS003010** [comment]
@invigorzz313 I have made a PR
Please do review and add necessary label

**Comment by AMS003010** [comment]
@Niketkumardheeryan i have made the PR. Please do review
