### ISSUE TITLE
Data Analysis and Price Forecasting of Crude Oil

### ISSUE THREAD

**Issue by ashis2004** [Niketkumardheeryan/ML-CaPsule#934]
In this feature we use Crudeoil as the target variable that we got to predict and we are going to use 6 features to do that (Gold, Silver, ChinaOilCorp, BTC(Bitcoin), Usdollar, NaturalGas).
here is some visualization of result after implementation 
![image](https://github.com/user-attachments/assets/a298c030-4aa5-4e1c-8325-04a80d164d46)
![image](https://github.com/user-attachments/assets/616472cc-919e-4759-9025-df9cd630a3d9)
pls assign it me @Niketkumardheeryan 
I'm contributor of GSsoc'24  i want to work on it

**Comment by Niketkumardheeryan** [comment]
Alreay there ,these kind of models..
