### ISSUE TITLE
Add Crude oil forecasting

### ISSUE THREAD

**Issue by pavitraag** [Niketkumardheeryan/ML-CaPsule#939]
The Crude Oil Forecasting project aims to predict future prices of crude oil using advanced machine learning and statistical techniques. Accurate forecasting of crude oil prices is critical for stakeholders in the energy sector, including producers, traders, and policymakers, as it helps in making informed decisions about production, investment, and policy.

**Comment by invigorzz313** [comment]
@pavitraag the issue is assigned.
