### ISSUE TITLE
SmartPhone Processor Classification

### ISSUE THREAD

**Issue by sreevidya-16** [Niketkumardheeryan/ML-CaPsule#950]
# Description
- This project aims to develop a system for classifying different smartphone processors based on collected data.
- By leveraging advanced data analysis and machine learning techniques, this project seeks to identify and categorize various processors used in smartphones, including those from leading manufacturers such as Qualcomm, Apple, Samsung, MediaTek, and Huawei.
- The system will analyze a wide range of data points, such as processing speed, core architecture, power efficiency, and performance benchmarks, to accurately classify each processor.
- This classification can aid consumers in making informed purchasing decisions, help manufacturers in market analysis, and assist developers in optimizing applications for specific processor types.
- Ultimately, this project will contribute to a better understanding of the competitive landscape of smartphone processors and their performance capabilities.

@Niketkumardheeryan, could you please assign me this issue under GSSOC'24, with appropriate labels ?

**Comment by invigorzz313** [comment]
@sreevidya-16 the issue is assigned.
