### ISSUE TITLE
Mobile price prediction model

### ISSUE THREAD

**Issue by aditya-bhaumik** [Niketkumardheeryan/ML-CaPsule#975]
Feature Description
I would like to add a model which is able to predict mobile prices properly

Use Case
Mobile price prediction is useful because it helps consumers decide the best time to buy a phone. It can also guide retailers in setting prices and managing stock. For beginners, creating a machine learning model for this task is a great way to learn about data analysis, feature selection, and model evaluation.

**Comment by aditya-bhaumik** [comment]
@invigorzz313 pls assign it to me I'm Gssoc'24 contributor

**Comment by aditya-bhaumik** [comment]
@Niketkumardheeryan please assign me this issue

**Comment by aditya-bhaumik** [comment]
please

**Comment by invigorzz313** [comment]
@aditya-bhaumik make sure to deploy.
