### ISSUE TITLE
Master card stock prediction model using lstm 

### ISSUE THREAD

**Issue by aditya-bhaumik** [Niketkumardheeryan/ML-CaPsule#976]
I would like to Add the ML Models which i am gonna build like using LSTM, SVM and K-Nearest Neighbors (KNN) using historical stock price data and relevant financial indicators, preprocess the data, performing EDA, and check the prices, and compare the model's accuracy.

**Comment by aditya-bhaumik** [comment]
@invigorzz313 pls assign it to me I'm Gssoc'24 contributor

**Comment by invigorzz313** [comment]
repititive
