### ISSUE TITLE
Stair Cases Segmentation

### ISSUE THREAD

**Issue by sreevidya-16** [Niketkumardheeryan/ML-CaPsule#993]
### Feature Description

I want to develop a  Stair Segmentation and Behavioral Cloning for Autonomous Stair Climbing

I got this idea by reading this [research paper](https://www.worldscientific.com/doi/abs/10.1142/S1793351X1940021X)

I want to implement this using PyTorch and Fast.ai library
@Niketkumardheeryan, @invigorzz313 sir could you please assign me this issue under GSSOC'24

### Use Case

Mobile robots are widely used in the surveillance industry, for military and industrial applications. In order to carry out surveillance tasks like urban search and rescue operation, the ability to traverse stairs is of immense significance. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sreevidya-16** [comment]
@Niketkumardheeryan, @invigorzz313 sir could you please assign me this issue under GSSOC'24

**Comment by Niketkumardheeryan** [comment]
A issue has been already assiyto you pls complete it first

**Comment by sreevidya-16** [comment]
@Niketkumardheeryan, view this PR

**Comment by sreevidya-16** [comment]
@invigorzz313, @Niketkumardheeryan kindly view this PR
